### ISSUE TITLE
raise 'no font file found'

### ISSUE THREAD

**Issue by sascha-hemi** [vwillcox/speedtest-cron#5]
Hi,
if i run the buttons.py after installation this error comes:

Traceback (most recent call last):
  File "./buttons.py", line 179, in <module>
    raise 'no font file found'
TypeError: exceptions must be old-style classes or derived from BaseException, not str

Greetings,
Sascha

**Comment by vwillcox** [comment]
Hi @sascha-hemi can you cofirm if you have the PaPiRus ePaper display or the E-paper HAT from http://www.percheron-electronics.uk/shop/e-paper-hat/
